version: 2
jobs:
  build:
    docker:
    - image: steveb8n/circle-sfdx:latest
    steps:
    - checkout
    - run:
        name: Create auth token
        command: echo $SFDC_AUTH > hubauth.txt
    - run:
        name: Authenticate to Hub Org (using sfdxurl flow)
        command: |
              sfdx force:auth:sfdxurl:store -f assets/sfdxurl.txt -d -a dreamhouse-org
              sfdx force:config:set defaultdevhubusername=salesforce.san@gmail.com --global
    - run:
        name: Remove auth token
        command: rm hubauth.txt
    - run:
        name: Create Scratch Org
        command: sfdx force:org:create --definitionfile config/project-scratch-def.json --durationdays 1 --setalias dreamhouse-org
    - run:
        name: Deploy Source
        command: sfdx force:source:push
    - run:
        name: Delete Scratch Org (ignoring bash return code)
        command: sfdx force:org:delete --noprompt --targetusername || true
        when: always
