version: 2
jobs:
  build:
    docker:
    - image: steveb8n/circle-sfdx:latest
    steps:
    - checkout
    - run:
        name: Create auth token
        command: echo $SFDC_AUTH > hubauth.txt
    - run:
        name: Authenticate to Hub Org (using sfdxurl flow)
        command: sfdx force:auth:sfdxurl:store -f assets/sfdxurl.txt --setdefaultusername dreamhouse-org -d -a dreamhouse-org
    - run:
        name: Remove auth token
        command: rm hubauth.txt
    - run:
        name: Create Scratch Org
        command: sfdx force:org:create --definitionfile config/project-scratch-def.json --durationdays 1 --setdefaultusername dreamhouse-org --setalias dreamhouse-org
    - run:
        name: Install Lightning Testing Service package
        command: sfdx force:lightning:test:install
    - run:
        name: Deploy Source
        command: sfdx force:source:push
    - run:
        name: Run Apex Tests
        command: sfdx force:apex:test:run --codecoverage --outputdir ~/junit --resultformat junit --wait 2
    - run:
        name: Run Lightning Testing Service Tests
        command: sfdx force:lightning:test:run --configfile config/lts-config.json --appname DiagramViewerTests.app --resultformat junit --outputdir ~/junit
    - store_test_results:
        path: ~/junit
    - run:
        name: Delete Scratch Org (ignoring bash return code)
        command: sfdx force:org:delete --noprompt --targetusername dreamhouse-org || true
        when: always
